version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A app.core.celery_app worker --loglevel=DEBUG -Q main-queue -c 4
    environment:
      DATABASE_URL: 'postgresql://postgres:password@postgres:5432/postgres'
      CELERY_RESULT_SERIALIZER: "json"
      CELERY_TASK_SERIALIZER: "json"
      CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
      CELERY_BROKER_URL: 'redis://redis:6379/0'

  flower:  
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    environment:
      DATABASE_URL: 'postgresql://postgres:password@postgres:5432/postgres'
    ports:  
        - 5555:5555
    depends_on:
      - "redis"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    ports:
      - 8888:8888
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:password@postgres:5432/postgres'
    depends_on:
      - "postgres"

volumes:
  db-data:
