"""job id changed as nullable parameter

Revision ID: 685e978b4139
Revises: f5e2c50ee080
Create Date: 2022-06-06 04:53:01.897575-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685e978b4139'
down_revision = 'f5e2c50ee080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
